spring:
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    show-sql: true

debug: true

site:
  protocol-and-host: http://localhost:8080
