spring:
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

site:
  protocol-and-host: http://localhost:8080
